sudo: require

services:
  - docker

before_install:
  - docker build -t bntzio/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bntzio/docker-react-app yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-110675843908"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
